name: Run Puppeteer Bot

on:
  schedule:
    - cron: "*/10 * * * *"  # chạy mỗi 30 phút
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer bot
        run: node bot.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"
