name: Run Puppeteer Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # chạy mỗi 5 phút
  workflow_dispatch:        # cho phép chạy thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer bot
        run: node bot.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
